fix

diff --git a/tools/release b/tools/release
--- a/tools/release
+++ b/tools/release
@@ -15,7 +15,6 @@ NODE_SPEC="package.json"
 CHANGELOG="docs/CHANGELOG.md"
 CONFIG="_config.yml"
 
-CSS_DIST="_sass/dist"
 JS_DIST="assets/js/dist"
 
 FILES=(
@@ -37,7 +36,7 @@ help() {
   echo "  2. Merge the release branch into the default branch"
   echo
   echo "Usage:"
-  echo "  bash $0 [options]"
+  echo "  bash ./tools/release [options]"
   echo
   echo "Options:"
   echo "  --prepare           Preparation for release"
@@ -56,13 +55,11 @@ _check_cli() {
 }
 
 _check_git() {
-  $opt_pre || (
-    # ensure that changes have been committed
-    if [[ -n $(git status . -s) ]]; then
-      echo "> Abort: Commit the staged files first, and then run this tool again."
-      exit 1
-    fi
-  )
+  # ensure that changes have been committed
+  if [[ -n $(git status . -s) ]]; then
+    echo "> Abort: Commit the staged files first, and then run this tool again."
+    exit 1
+  fi
 
   $opt_pkg || (
     if [[ "$(git branch --show-current)" != "$RELEASE_BRANCH" ]]; then
@@ -82,12 +79,17 @@ _check_src() {
   done
 }
 
-init() {
+_check_node_packages() {
+  if [[ ! -d node_modules || "$(du node_modules | awk '{print $1}')" == "0" ]]; then
+    npm i
+  fi
+}
+
+check() {
   _check_cli
   _check_git
   _check_src
-  echo -e "> npm install\n"
-  npm i
+  _check_node_packages
 }
 
 ## Bump new version to gem-spec file
@@ -111,20 +113,28 @@ prepare() {
 
 ## Build a Gem package
 build_gem() {
+  if $opt_pkg; then
+    BACKUP_PATH="$(mktemp -d)"
+    cp "$JS_DIST"/* "$BACKUP_PATH"
+  fi
+
   # Remove unnecessary theme settings
-  sed -i -E "s/(^timezone:).*/\1/;s/(^cdn:).*/\1/;s/(^avatar:).*/\1/" $CONFIG
+  sed -i "s/^cdn:.*/cdn:/;s/^avatar:.*/avatar:/" $CONFIG
   rm -f ./*.gem
 
   npm run build
-  # add CSS/JS distribution files to gem package
-  git add "$CSS_DIST" "$JS_DIST" -f
-
-  echo -e "\n> gem build $GEM_SPEC\n"
+  git add "$JS_DIST" -f # add JS distribution files to gem
   gem build "$GEM_SPEC"
 
-  echo -e "\n> Resume file changes ...\n"
+  # resume the settings
   git reset
   git checkout .
+
+  if $opt_pkg; then
+    # restore the dist files for future development
+    mkdir -p "$JS_DIST" && cp "$BACKUP_PATH"/* "$JS_DIST"
+    rm -rf "$BACKUP_PATH"
+  fi
 }
 
 # Push the gem to RubyGems.org (using $GEM_HOST_API_KEY)
@@ -147,7 +157,7 @@ merge() {
 }
 
 main() {
-  init
+  check
 
   if $opt_pre; then
     prepare
